# -*- coding: utf-8 -*-
"""main.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1wxbhhnDhHIiv9zDTqfXLjKq0R3J2i1j0
"""

from fastapi import FastAPI
from fastapi.staticfiles import StaticFiles
from pydantic import BaseModel
from openai import OpenAI
from dotenv import load_dotenv
import os
from fastapi.middleware.cors import CORSMiddleware
import uvicorn

# ---------------- Load API key ----------------
load_dotenv()
api_key = os.getenv("API_KEY")
if not api_key:
    raise ValueError("API_KEY not set in environment variables!")

# ---------------- FastAPI app ----------------
app = FastAPI(title="Chatbot API")

# ---------------- CORS ----------------
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_methods=["*"],
    allow_headers=["*"],
)

# ---------------- Serve static files ----------------
app.mount("/static", StaticFiles(directory="static"), name="static")

# ---------------- OpenAI / OpenRouter client ----------------
base_url = "https://openrouter.ai/api/v1"
client = OpenAI(base_url=base_url, api_key=api_key)

# ---------------- Data models ----------------
class ChatRequest(BaseModel):
    message: str
    role: str
    style: str
    length: str
    history: list[list[str]]

# ---------------- Chatbot config ----------------
chatbot_roles = {
    "Teacher": "You are a teacher who explains things clearly.",
    "Friend": "You are a friend who listens and supports the user.",
    "Advisor": "You are an advisor who offers practical guidance.",
    "Casual": "You are a chatbot that speaks naturally.",
    "Mentor": "You are a career mentor who gives advice."
}

chat_styles = {
    "Formal": "Speak politely and use professional language.",
    "Friendly": "Speak warmly and casually with emojis 😊.",
    "Sarcastic": "Use light sarcasm and humor 😏.",
    "Poetic": "Respond creatively and use expressive language 🎭."
}

reply_length = {
    "Detailed": "Give a detailed answer with explanation of 5–6 lines.",
    "Short": "Give a concise answer not more than 2 lines."
}

# ---------------- Chat endpoint ----------------
@app.post("/chat")
async def chat(request: ChatRequest):
    role_prompt = chatbot_roles.get(request.role, "You are a chatbot that speaks naturally.")
    style_prompt = chat_styles.get(request.style, "")
    length_prompt = reply_length.get(request.length, "")
    system_prompt = f"{role_prompt}\n{style_prompt}\n{length_prompt}"

    messages = [{"role": "system", "content": system_prompt}]
    for item in request.history:
        if len(item) == 2:
            user_msg, bot_msg = item
            messages.append({"role": "user", "content": user_msg})
            messages.append({"role": "assistant", "content": bot_msg})

    messages.append({"role": "user", "content": request.message})

    try:
        response = client.chat.completions.create(
            model="mistralai/mistral-7b-instruct",
            max_tokens=1000,
            temperature=0.7,
            messages=messages
        )
        reply = response.choices[0].message.content
    except Exception as e:
        return {"error": str(e)}

    new_history = request.history + [[request.message, reply]]
    return {"reply": reply, "history": new_history}

# ---------------- Extra endpoints ----------------
@app.get("/chatbot_roles")
async def get_chatbot_roles():
    return chatbot_roles

@app.get("/chat_styles")
async def get_chat_styles():
    return chat_styles

@app.get("/reply_length")
async def get_reply_length():
    return reply_length

@app.get("/reset")
async def reset_history():
    return {"history": []}

# ---------------- Root endpoint ----------------
@app.get("/")
def home():
    return {"message": "Hello, Render!"}

# ---------------- Run app ----------------
if __name__ == "__main__":
    port = int(os.environ.get("PORT", 8000))
    uvicorn.run(app, host="0.0.0.0", port=port)